version: '3.8'

services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql_financial
    environment:
      MYSQL_ROOT_PASSWORD: 1234###
      MYSQL_DATABASE: financial_db
      MYSQL_USER: financial_user
      MYSQL_PASSWORD: financial_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
